#tomcat port
server:
  port: 9001
#jsp
spring:
  #mvc:
    #view:
      #prefix: /WEB-INF/
      #suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bobsajo?serverTimezone=Asia/Seoul
    username: bobsajo
    password: a4Pff4JorngVDyd
#mybatis
mybatis:
  type-aliases-package: boot.data.dto,boot.data.mapper
  mapper-locations:
  - /mapper/**/*.xml #mapper 폴더 안에 어느 폴더에 있든 xml로 끝나는 파일      

